# Generated by Django 3.1 on 2020-09-10 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='stack',
            field=models.TextField(default=-1.0),
            preserve_default=False,
        ),
    ]
